### ISSUE TITLE
Storing mess.frm on Slack with Shelf storage backend does not work

### ISSUE THREAD

**Issue by br0ziliy** [errbotio/errbot#771]
Following traceback is generated when storing an Identifier using Slack backend:

```
09:10:32 ERROR    errbot.errBot             An error happened while processing a message ("some message"): Traceback (most recent call last):
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/errBot.py", line 482, in _execute_and_send
    for reply in replies:
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/__init__.py", line 386, in wrapper
    yield func(self, mess, *func_args, **func_kwargs)
  File "/opt/err-plugins/err-ansible/ansible.py", line 111, in ansible_cmd
    raw_result = tasks.run_task(self, ansible_cmd, _from)
  File "/opt/err-plugins/err-ansible/lib/tasks.py", line 22, in run_task
    bot['tasks'] = tasklist
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/storage/__init__.py", line 50, in __setitem__
    return self._store.set(key, item)
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/storage/shelf.py", line 28, in set
    self.shelf[key] = value
  File "/usr/lib64/python2.7/shelve.py", line 132, in __setitem__
    p.dump(value)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

The code I use:
```
    # botplugin.py
    @arg_botcmd('ansible_cmd', type=str, \
                help="param for the command")
    def ansible(self, mess, param1=None):
        ...
        _from = mess.frm
        raw_result = tasks.run_task(self, ansible_cmd, _from)
        return result

    # tasks.py
def run_task(bot, cmd, _from):
      bot['tasks'] = tasklist
      tasklist[cmd] = _from
      bot['tasks'] = tasklist # fails here
```
If I try to pickle the mess.frm with Slack backend (for debugging):

```
Traceback (most recent call last):
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/errBot.py", line 482, in _execute_and_send
    for reply in replies:
  File "/home/devops_bot/ve/lib/python2.7/site-packages/errbot/__init__.py", line 386, in wrapper
    yield func(self, mess, *func_args, **func_kwargs)
  File "/opt/err-plugins/err-ansible/ansible.py", line 96, in ansible_cmd
    p.dumps(_from)
  File "/usr/lib64/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/home/devops_bot/ve/lib64/python2.7/copy_reg.py", line 77, in _reduce_ex
    raise TypeError("a class that defines __slots__ without "
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

I tried to use Telegram backend - and my plugin works fine there (and pickling mess.frm with Telegram backend works too.
I suppose there's some issue in SlackPerson class that prevents it from being pickled?

**Comment by zoni** [comment]
Identifiers aren't really meant to be pickled and stored. Which is not to say we won't accept pull-requests that make them pickleable though. :smile: 

Speaking purely for myself, it's unlikely I'll delve into this, but all hope is not lost. The recommended way to do this is to store the string representation of a given identifier instead. When you then need to turn that string back into a usable identifier, call `self.build_identifier()` on it.

Is that a workable solution for you?

**Comment by zoni** [comment]
Although, thinking more about it, we really ought to fix it either way. It's quite likely to trip people up otherwise. Still, for me personally it's not at the top of the list considering all the other things that need doing and there being a viable workaround, so anyone willing to give this a try is more than welcome to.

**Comment by br0ziliy** [comment]
> Identifiers aren't really meant to be pickled and stored

Yeah, I thought so

> not to say we won't accept pull-requests that make them pickleable though. :smile:

Any pointers with where to start, before I go and dig out how SlackPerson identifier is different from others?

> The recommended way to do this is to store the string representation of a given identifier instead

Yeah, I was thinking about that, and I like that more - but I could not find a way to get `txtrep` from already built Identifier.
Does it make sense to add `get_txtrep()` method to Person or Identifier class?

**Comment by zoni** [comment]
> Any pointers with where to start, before I go and dig out how SlackPerson identifier is different from others?

I'm not sure, and the traceback doesn't give appear to give any helpful pointers either, sadly. My guess is that it might have something to do with `SlackPerson` holding a reference to the `SlackClient()` which is used to interface with slack. If it is indeed that, then that will in turn make this very tricky to solve most likely :disappointed: 

 > but I could not find a way to get `txtrep` from already built Identifier.

All identifiers have a `__str__()` method which returns a string-representation which is compatible with `build_identifier()`, so it's actually as simple as doing `_from = str(mess.frm)`.

**Comment by br0ziliy** [comment]
> All identifiers have a __str__() method

Hah! Overlooked that. In this case my issue is easily solved by storing the string representation and than rebuilding an Identofier with `self.build_identifier()`. That's more than enough.

I think this report can be closed since the Identifiers aren't meant to be pickled/stored anyway, and the effort needed to make it work does not actually cover the value added. It's better to just mention this in the docs somewhere.
Is there a possibility to send a pull request to the documentation which will clarify this behaviour of Identifiers?

**Comment by gbin** [comment]
Ultimately I think it is preferable that Identifiers override the pickling and play nice with it.

What @br0ziliy did seems totally natural API wise: we give an identifier for you to handle/store/compare etc.. , we also give a storage feature, they should be compatible :).

**Comment by zoni** [comment]
I do agree, but on the short-term, I'm not sure it's worth the effort required compared to some of the other issues people are still facing.

**Comment by gbin** [comment]
I have added the pickling tests to the backend tester.
